BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Student_Hall_History';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Room_History';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Guest_log';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_GuestLog';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Hall_Head_History';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Staff_worksAt_Hall';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Student_forms_Team';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Winner_List';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Team_Event_History';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Inter_Hall_Team';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Application_room_list';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Application';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/







BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Allowed_Guest';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/









begin
   execute immediate 'drop table table_Student';
exception
   when others then null;
end;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Room';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_event';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/





BEGIN
   execute immediate 'drop table table_teacher';
exception
   when others then null;
end;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_team';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_staff';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_Guest';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE table_hall';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
