CREATE OR REPLACE VIEW VW_GUEST AS SELECT
	g.NID,
	( g.FIRST_NAME || ' ' || g.LAST_NAME ) "NAME",
	g.CONTACT_NO,
	g.ADDRESS 
FROM
	TABLE_GUEST g;







CREATE OR REPLACE VIEW VW_TEACHER AS SELECT
	t.ID,
	t.PASSWORD,
	( t.FIRST_NAME || ' ' || t.LAST_NAME ) "NAME",
	t.CONTACT_NO,
	t.DEPARTMENT_ID,
	t.DESIGNATION,
	FUNC_MALE_OR_FEMALE(t.GENDER) "GENDER"
FROM
	"TABLE_TEACHER" t;
	
	




CREATE OR REPLACE VIEW VW_STUDENT AS
SELECT 
    ID ,
    ( s.FIRST_NAME || ' ' || s.LAST_NAME ) "NAME",
    DEPARTMENT_ID ,
    ADDRESS ,
    BLOOD_GROUP ,
    BIRTH_DATE ,
    TYPE ,
    s.HALL_ID "HALL_ID",
    (SELECT h.HALL_NAME FROM TABLE_HALL h where h.HALL_ID=s.HALL_ID)"HALL_NAME",
    RELIGION ,
    FUNC_MALE_OR_FEMALE(GENDER) "GENDER",
    PASSWORD ,
    FATHER_NAME ,
    MOTHER_NAME ,
    CONTACT_NO 
FROM TABLE_STUDENT s;





CREATE OR REPLACE VIEW VW_STUDENT_GUEST_LIST AS
SELECT 
	s.ID "STUDENT_ID" ,
	s.NAME "STUDENT_NAME",
	s.ADDRESS "STUDENT_ADDRESS",
	INITCAP(TYPE) "STUDENT_TYPE",
	s.HALL_NAME "HALL_NAME",
	s.GENDER "STUDENT_GENDER",
	s.CONTACT_NO "STUDENT_CONTACT_NO",
	g.NAME "GUEST_NAME",
	g.CONTACT_NO "GUEST_CONTACT_NO",
	g.ADDRESS "GUEST_ADDRESS",
	INITCAP(ag.RELATION) "RELATION_WITH_GUEST"
FROM VW_STUDENT s left join TABLE_ALLOWED_GUEST ag on (s.ID=ag.STUDENT_ID) join VW_GUEST g on (ag.NID=g.NID);
	


	

	
CREATE OR REPLACE VIEW VW_GUEST_STUDENT_LIST AS
SELECT 
	g.NID "GUEST_NID",
	g.NAME "GUEST_NAME",
	g.CONTACT_NO "GUEST_CONTACT_NO",
	g.ADDRESS "GUEST_ADDRESS",
	s.ID "STUDENT_ID" ,
	s.NAME "STUDENT_NAME",
	s.HALL_NAME "HALL_NAME",
	s.GENDER "STUDENT_GENDER",
	s.CONTACT_NO "STUDENT_CONTACT_NO",
	INITCAP(ag.RELATION) "RELATION_WITH_GUEST"
FROM VW_STUDENT s join TABLE_ALLOWED_GUEST ag on (s.ID=ag.STUDENT_ID) right join VW_GUEST g on (ag.NID=g.NID)
ORDER BY g.NID;
	










CREATE VIEW VW_GUEST_STD_COUNT AS
SELECT g.NID NID,
g.FIRST_NAME FIRST_NAME,
g.LAST_NAME LAST_NAME,
g.CONTACT_NO CONTACT_NO,
g.ADDRESS ADDRESS,
( SELECT COUNT(ag.STUDENT_ID) FROM TABLE_ALLOWED_GUEST ag where (g.NID=ag.NID) ) "Current_no_of_students"
FROM TABLE_GUEST g;




CREATE OR REPLACE VIEW VW_STUDENT_EVENT_PART_LOG AS
SELECT STD.ID,STDTM.TEAM_ID,EV.EVENT_ID, EV.EVENT_NAME, EV.EVENT_YEAR, EV.EVENT_SPORT, EV.EVENT_TYPE, EV.EVENT_STATUS, EV.HALL_ID, EV.EVENT_SUPERVISOR_ID, EV.WINNER_TEAM_ID, EV.RUNNERUP_TEAM_ID 
FROM VW_STUDENT STD join TABLE_STUDENT_FORMS_TEAM STDTM on (STD.ID = STDTM.STUDENT_ID) join TABLE_TEAM TM on ( STDTM.TEAM_ID = TM.TEAM_ID) join TABLE_TEAM_EVENT_HISTORY TEV on (TEV.TEAM_ID = TM.TEAM_ID) join TABLE_EVENT EV on (TEV.EVENT_ID = EV.EVENT_ID) 
WHERE UPPER(EV.EVENT_STATUS) = 'OVER';